import { randomUUID } from "node:crypto";
import { closeSync, constants, fchmodSync, lstatSync, mkdirSync, openSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const PLUGIN_ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const MAX_CONFIG_BYTES = 16 * 1024;
const MARKER = "# Generated by Useful Skills";
const PRIVATE_DIRECTORY_MODE = 0o700;

/** Plugin agent -> model role, matching OMP's task.agentModelOverrides. */
export const ROLE_AGENTS = Object.freeze({
  planner: "plan",
  scout: "research",
  frontend: "frontend",
  backend: "backend",
  "general-purpose": "implementation",
  reviewer: "review",
  "security-reviewer": "security",
});

export const ROLES = Object.freeze(["research", "frontend", "backend", "implementation", "review", "security", "plan", "default"]);
const EFFORTS = new Set(["low", "medium", "high", "xhigh", "max"]);
const MODEL = /^(inherit|opus|sonnet|haiku|fable|claude-[a-z0-9][a-z0-9.-]{0,80})$/;

export const DEFAULT_ROLES = Object.freeze({
  research: "claude-haiku-5-5:high",
  frontend: "claude-sonnet-5-5:high",
  backend: "claude-opus-5-5:high",
  implementation: "claude-sonnet-5-5:high",
  review: "claude-sonnet-5-5:medium",
  security: "claude-opus-5-5:high",
  plan: "claude-opus-5-5:high",
  default: "claude-opus-5-5:medium",
});

export function claudeConfigDir(environment = process.env) {
  return environment.CLAUDE_CONFIG_DIR || path.join(os.homedir(), ".claude");
}

export function modelsConfigPath(configDir) {
  return path.join(configDir, "useful-skills", "models.yml");
}

export function generatedAgentName(agent) {
  return `us-${agent}`;
}

function agentFile(configDir, agent) {
  return path.join(configDir, "agents", `useful-skills-${agent}.md`);
}

function defaultConfig() {
  const rows = ROLES.map(role => `  ${role}: ${DEFAULT_ROLES[role]}`);
  return [
    "# Useful Skills model roles for Claude Code.",
    "# Selector: <model>[:<effort>]. Model is a Claude model ID or alias (opus, sonnet, haiku, fable, inherit);",
    "# an OMP-style \"anthropic/\" prefix is accepted. Effort: low, medium, high, xhigh, max.",
    "# A missing role uses `default`. Changes apply to Claude Code sessions started afterwards.",
    "modelRoles:",
    ...rows,
    "",
  ].join("\n");
}

/** Parse one `<model>[:<effort>]` selector, or throw a message naming the role. */
export function parseSelector(role, raw) {
  const [model, effort, extra] = raw.replace(/^anthropic\//, "").split(":");
  if (extra !== undefined || !MODEL.test(model) || (effort !== undefined && !EFFORTS.has(effort))) {
    throw new Error(`Invalid selector for role "${role}". Use <model>[:<effort>], for example claude-opus-5-5:high.`);
  }
  return { model, effort };
}

/** A strict YAML subset: comments, a `modelRoles:` key, and indented `role: selector` rows. */
export function parseModelsConfig(text) {
  const roles = {};
  let inRoles = false;
  for (const [index, row] of text.split(/\r?\n/).entries()) {
    const line = row.replace(/\s+#.*$/, "").trimEnd();
    if (!line.trim() || line.trimStart().startsWith("#")) continue;
    if (line === "modelRoles:") {
      inRoles = true;
      continue;
    }
    const entry = /^\s+([a-z]+):\s*(["']?)([^"'\s]+)\2$/.exec(line);
    if (!inRoles || !entry) {
      throw new Error(`Unsupported content on line ${index + 1}; expected \`modelRoles:\` followed by indented \`role: selector\` rows.`);
    }
    const [, role, , selector] = entry;
    if (!ROLES.includes(role)) {
      throw new Error(`Unknown role "${role}" on line ${index + 1}. Known roles: ${ROLES.join(", ")}.`);
    }
    if (Object.hasOwn(roles, role)) {
      throw new Error(`Role "${role}" is defined more than once.`);
    }
    roles[role] = parseSelector(role, selector);
  }
  if (!inRoles) {
    throw new Error("Missing `modelRoles:` section.");
  }
  return roles;
}

function readText(file) {
  const text = readFileSync(file, "utf8");
  if (Buffer.byteLength(text) > MAX_CONFIG_BYTES) {
    throw new Error("Model configuration exceeds 16 KiB.");
  }
  return text;
}

/**
 * The workflow settings store requires `<configDir>/useful-skills` to be private, so create it
 * owner-only and tighten an existing real directory. Best effort: a symlink, non-directory, or
 * permission failure is left for the store to report instead of failing SessionStart here.
 */
function ensurePrivateDirectory(directory) {
  try {
    mkdirSync(path.dirname(directory), { recursive: true });
    mkdirSync(directory, { mode: PRIVATE_DIRECTORY_MODE });
  } catch {
    // Already present, or unwritable; the checks below and later writes decide what happens.
  }

  let descriptor;
  try {
    if (!lstatSync(directory).isDirectory()) {
      return;
    }

    // Open the directory itself, not a symlink destination, before changing its permissions.
    descriptor = openSync(directory, constants.O_RDONLY | constants.O_DIRECTORY | constants.O_NOFOLLOW);
    fchmodSync(descriptor, PRIVATE_DIRECTORY_MODE);
  } catch {
    // Missing, replaced, or not ours to change; the settings store reports the resulting state.
  } finally {
    if (descriptor !== undefined) {
      closeSync(descriptor);
    }
  }
}

function writeAtomic(file, text) {
  mkdirSync(path.dirname(file), { recursive: true });
  const temporary = `${file}.${randomUUID()}.tmp`;
  try {
    writeFileSync(temporary, text, { flag: "wx", mode: 0o644 });
    renameSync(temporary, file);
  } finally {
    rmSync(temporary, { force: true });
  }
}

function readOptional(file) {
  try {
    return readFileSync(file, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") return undefined;
    throw error;
  }
}

/** Split a bundled plugin agent into its simple frontmatter fields and body. */
function pluginAgent(agent, pluginRoot) {
  const text = readFileSync(path.join(pluginRoot, "claude", "agents", `${agent}.md`), "utf8");
  const match = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(text);
  if (!match) throw new Error(`Bundled agent ${agent} has no frontmatter.`);
  const fields = Object.fromEntries(match[1].split("\n").map(row => {
    const separator = row.indexOf(":");
    return [row.slice(0, separator).trim(), row.slice(separator + 1).trim()];
  }));
  return { fields, body: match[2] };
}

export function renderAgent(agent, selection, { pluginRoot = PLUGIN_ROOT, configFile }) {
  const { fields, body } = pluginAgent(agent, pluginRoot);
  // Generated agents live outside the plugin, so plugin-relative references become absolute.
  const resolvedBody = body.replaceAll("the plugin's `claude/", `\`${path.join(pluginRoot, "claude")}/`);
  return [
    "---",
    `${MARKER} from ${configFile} (role: ${ROLE_AGENTS[agent]}). Edit that file instead; this file is overwritten.`,
    `name: ${generatedAgentName(agent)}`,
    `description: ${fields.description}`,
    `tools: ${fields.tools}`,
    `model: ${selection.model}`,
    ...(selection.effort ? [`effort: ${selection.effort}`] : []),
    "---",
    resolvedBody,
  ].join("\n");
}

function selectionFor(roles, agent) {
  return roles[ROLE_AGENTS[agent]] ?? roles.default ?? { model: "inherit" };
}

/**
 * Create the model config on first use and regenerate the Claude role agents from it.
 * Never overwrites an agent file that Useful Skills did not generate.
 */
export function syncRoleAgents({ configDir = claudeConfigDir(), pluginRoot = PLUGIN_ROOT } = {}) {
  const configFile = modelsConfigPath(configDir);
  ensurePrivateDirectory(path.dirname(configFile));

  let created = false;
  if (readOptional(configFile) === undefined) {
    writeAtomic(configFile, defaultConfig());
    created = true;
  }

  let roles;
  try {
    roles = parseModelsConfig(readText(configFile));
  } catch (error) {
    return { configFile, created, error: error.message, agents: {} };
  }

  const agents = {};
  for (const agent of Object.keys(ROLE_AGENTS)) {
    const file = agentFile(configDir, agent);
    const selection = selectionFor(roles, agent);
    const existing = readOptional(file);
    if (existing !== undefined && !existing.includes(`\n${MARKER} `)) {
      agents[agent] = { state: "conflict", file, selection };
      continue;
    }
    const next = renderAgent(agent, selection, { pluginRoot, configFile });
    if (existing === next) {
      agents[agent] = { state: "ready", file, selection };
    } else {
      writeAtomic(file, next);
      agents[agent] = { state: existing === undefined ? "created" : "updated", file, selection };
    }
  }
  return { configFile, created, agents };
}

function describe({ model, effort }) {
  return effort ? `${model}, effort ${effort}` : model;
}

/** Session context naming which agent to dispatch for each plugin role. */
export function modelRoutingContext(result) {
  const lines = [`Useful Skills model roles are configured in ${result.configFile}${result.created ? " (created with defaults this session)" : ""}.`];
  if (result.error) {
    lines.push(`That file is invalid: ${result.error} Role agents were not regenerated; previously generated \`us-*\` agents keep their earlier models. Tell the user once so they can fix the file.`);
  }
  const pending = [];
  for (const [agent, info] of Object.entries(result.agents)) {
    const plugin = `useful-skills:${agent}`;
    if (info.state === "conflict") {
      lines.push(`- ${plugin}: ${info.file} exists but was not generated by Useful Skills; dispatch \`${plugin}\` (inherits the session model).`);
      continue;
    }
    lines.push(`- ${plugin}: dispatch \`${generatedAgentName(agent)}\` (${describe(info.selection)}).`);
    if (info.state !== "ready") pending.push(generatedAgentName(agent));
  }
  if (Object.keys(result.agents).length) {
    lines.unshift("When a Useful Skills skill names a `useful-skills:<agent>` subagent, dispatch the configured role agent listed below with the same brief and boundaries; do not pass a `model` in the Agent call.");
    lines.push("If a listed `us-*` agent type is unavailable in this session, dispatch the named `useful-skills:<agent>` instead and report that it ran on the inherited session model.");
  }
  if (pending.length) {
    lines.push(`Created or updated this session (load after Claude Code restarts): ${pending.join(", ")}.`);
  }
  return lines.join("\n");
}
